### PR TITLE
Best time only

### PR DESCRIPTION
**Pull request by ChristyDotDev**
Just shows your best time on the track leaderboard. Meant I couldn't sort in the graphql (I think) so moved that to the JS

### CODE REVIEW

**Comment by ChristyDotDev** [comment]
```
query TrackLeaderBoardQuery {
  driver(where: {}) {
    laps(where: {session_leaderboard_line_laps: {session_leaderboard_line: {session_leader_board_lines: {session: {track_name: {_eq: "zandvoort_2020"}}}}, lap: {valid_for_best: {_eq: true}}}, lap_time: {}}, order_by: {lap_time: asc}, limit: 1) {
      lap_time
    }
    first_name
    last_name
    player_id
    short_name
  }
}
```

Something like this might do it

**Comment by Eeeeeeeeeeeeen** [comment]
Something doesn't seem right, not showing the fastest laps

**Comment by ChristyDotDev** [comment]
> Something doesn't seem right, not showing the fastest laps

Aye, I noticed the second I sent you it that it wasn't sorting on the Hasura side. Pushed an update now

**Comment by Eeeeeeeeeeeeen** [comment]
To whom this may concern:

:+1:

Sincerely
Ian

**Review by Eeeeeeeeeeeeen — APPROVED** [review]

**Pull request merged**
